-- MySQL Script generated by MySQL Workbench
-- mer. 15 mars 2023 14:22:32
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Statistiques`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Statistiques` (
  `Carburant` INT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Historique`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Historique` (
  `idHistorique` INT NOT NULL,
  `heure_de_depart` VARCHAR(45) NULL,
  PRIMARY KEY (`idHistorique`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`chariot`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`chariot` (
  `id` INT NOT NULL,
  `est_opperationnel` TINYINT NOT NULL,
  `annee` INT NOT NULL,
  `est_parti` TINYINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`statistiques`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`statistiques` (
  `id` INT NOT NULL,
  `carburant` INT NULL COMMENT 'L',
  `vitesse` INT NULL COMMENT 'km/h',
  `clignotantDroit` TINYINT NULL,
  `clignotantGauche` TINYINT NULL,
  `nb_tours` INT NULL COMMENT 'tr/min',
  `phares_allumes` TINYINT NULL,
  `plein_phares` TINYINT NULL,
  `ceinture_conducteur_attachee` TINYINT NULL,
  `stop` TINYINT NOT NULL,
  `batterie_rechargement` TINYINT NULL,
  `affichage_heure` TIME NOT NULL,
  `liquide_refroidissement_moteur` TINYINT NULL,
  `frein_a_main` TINYINT NOT NULL,
  `temperature_ext` INT NULL COMMENT '°C',
  `chariot_id` INT NOT NULL,
  PRIMARY KEY (`id`, `chariot_id`),
  INDEX `fk_Statistiques_Chariot1_idx` (`chariot_id` ASC) VISIBLE,
  CONSTRAINT `fk_Statistiques_Chariot1`
    FOREIGN KEY (`chariot_id`)
    REFERENCES `mydb`.`chariot` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`historique`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`historique` (
  `id` INT NOT NULL,
  `heure_de_depart` VARCHAR(45) NOT NULL,
  `heure_arrivee` VARCHAR(45) NOT NULL,
  `chariot_id` INT NOT NULL,
  PRIMARY KEY (`id`, `chariot_id`),
  INDEX `fk_Historique_Chariot_idx` (`chariot_id` ASC) VISIBLE,
  CONSTRAINT `fk_Historique_Chariot`
    FOREIGN KEY (`chariot_id`)
    REFERENCES `mydb`.`chariot` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`comptage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`comptage` (
  `id` INT NOT NULL,
  `nb_chariots_partis` INT NULL,
  `nb_chariots` INT NOT NULL,
  `nb_chariots_restants` INT NOT NULL,
  `nb_chariots_HS` INT NULL,
  `chariot_id` INT NOT NULL,
  PRIMARY KEY (`id`, `chariot_id`),
  INDEX `fk_Comptage_Chariot1_idx` (`chariot_id` ASC) VISIBLE,
  CONSTRAINT `fk_Comptage_Chariot1`
    FOREIGN KEY (`chariot_id`)
    REFERENCES `mydb`.`chariot` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`alarmes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`alarmes` (
  `id` INT NOT NULL,
  `user` VARCHAR(45) NOT NULL,
  `machine` VARCHAR(45) NOT NULL,
  `alerte_refroidissement_moteur` TINYINT NULL,
  `eau_moteur` TINYINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
