-- MySQL Script generated by MySQL Workbench
-- jeu. 09 mars 2023 15:09:33
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Statistiques`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Statistiques` (
  `IDStats` INT NOT NULL,
  `Carburant` INT NULL COMMENT 'L',
  `Vitesse` INT NULL COMMENT 'km/h',
  `ClignotantDroit` TINYINT NULL,
  `ClignotantGauche` TINYINT NULL,
  `nb_tours` INT NULL COMMENT 'tr/min',
  `phares_allumes` TINYINT NULL,
  `plein_phares` TINYINT NULL,
  `Ceinture_conducteur_attachee` TINYINT NULL,
  `Stop` TINYINT NULL,
  `Batterie_rechargement` TINYINT NULL,
  `Affichage_heure` VARCHAR(45) NULL,
  `liquide_refroidissement_moteur` TINYINT NULL,
  `Frein_a_main` TINYINT NULL,
  `temperature_ext` INT NULL COMMENT '°C',
  PRIMARY KEY (`IDStats`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Chariot`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Chariot` (
  `idChariot` INT NOT NULL,
  `est_opperationnel` TINYINT NULL,
  `Annee` INT NULL,
  `Est_parti` TINYINT NULL,
  PRIMARY KEY (`idChariot`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Historique`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Historique` (
  `idHistorique` INT NOT NULL,
  `heure_de_depart` VARCHAR(45) NULL,
  `heure_arrivee` VARCHAR(45) NULL,
  `Chariot_idChariot` INT NOT NULL,
  PRIMARY KEY (`idHistorique`),
  INDEX `fk_Historique_Chariot_idx` (`Chariot_idChariot` ASC) VISIBLE,
  CONSTRAINT `fk_Historique_Chariot`
    FOREIGN KEY (`Chariot_idChariot`)
    REFERENCES `mydb`.`Chariot` (`idChariot`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Statistiques`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Statistiques` (
  `IDStats` INT NOT NULL,
  `Carburant` INT NULL COMMENT 'L',
  `Vitesse` INT NULL COMMENT 'km/h',
  `ClignotantDroit` TINYINT NULL,
  `ClignotantGauche` TINYINT NULL,
  `nb_tours` INT NULL COMMENT 'tr/min',
  `phares_allumes` TINYINT NULL,
  `plein_phares` TINYINT NULL,
  `Ceinture_conducteur_attachee` TINYINT NULL,
  `Stop` TINYINT NULL,
  `Batterie_rechargement` TINYINT NULL,
  `Affichage_heure` VARCHAR(45) NULL,
  `liquide_refroidissement_moteur` TINYINT NULL,
  `Frein_a_main` TINYINT NULL,
  `temperature_ext` INT NULL COMMENT '°C',
  PRIMARY KEY (`IDStats`))
ENGINE = InnoDB;




-- -----------------------------------------------------
-- Table `mydb`.`Historique`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Historique` (
  `idHistorique` INT NOT NULL,
  `heure_de_depart` VARCHAR(45) NULL,
  `heure_arrivee` VARCHAR(45) NULL,
  `Chariot_idChariot` INT NOT NULL,
  PRIMARY KEY (`idHistorique`),
  INDEX `fk_Historique_Chariot_idx` (`Chariot_idChariot` ASC) VISIBLE,
  CONSTRAINT `fk_Historique_Chariot`
    FOREIGN KEY (`Chariot_idChariot`)
    REFERENCES `mydb`.`Chariot` (`idChariot`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Comptage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Comptage` (
  `idComptage` INT NOT NULL,
  `nb_chariots_partis` INT NULL,
  `nb_chariots` INT NULL,
  `nb_chariots_restants` INT NULL,
  `nb_chariots_HS` INT NULL,
  PRIMARY KEY (`idComptage`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`alarmes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`alarmes` (
  `idalarmes` INT NOT NULL,
  `user` VARCHAR(45) NULL,
  `machine` VARCHAR(45) NULL,
  `alerte_refroidissement_moteur` TINYINT NULL,
  `eau_moteur` TINYINT NULL,
  PRIMARY KEY (`idalarmes`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
