-- MySQL Script generated by MySQL Workbench
-- ven. 02 juin 2023 11:43:37
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`demo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`demo` (
  `iddemo` INT NOT NULL,
  `demonstration` VARCHAR(45) NULL,
  `demonstration_nn` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`iddemo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`demo-II`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`demo-II` (
  `demo_iddemo` INT NOT NULL,
  INDEX `fk_demo-II_demo_idx` (`demo_iddemo` ASC) VISIBLE,
  CONSTRAINT `fk_demo-II_demo`
    FOREIGN KEY (`demo_iddemo`)
    REFERENCES `mydb`.`demo` (`iddemo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
